apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: dse-experiments
spec:
  slotsPerWorker: 8
#  restartPolicy: OnFailure
  restartPolicy: Never
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
            - image: ajliang/dse-experiments
              name: dse-experiments
              command:
                - mpirun
                - --allow-run-as-root
                - -np
                - "8"
                - -bind-to
                - none
                - -map-by
                - slot
                - -x
                - NCCL_DEBUG=INFO
                - -x
                - LD_LIBRARY_PATH
                - -x
                - PATH
                - -mca
                - pml
                - ob1
                - -mca
                - btl
                - ^openib
                - python
                - pretrain_gpt2.py
                - --model-parallel-size=1
                - --pipe-parallel-size=1
                - --num-layers=24
                - --hidden-size=1024
                - --num-attention-heads=16
                - --seq-length=1024
                - --max-position-embeddings=1024
                - --batch-size=2
                - --gas=1
                - --train-iters=320000
                - --lr-decay-iters=320000
                - --data-path=/hot/preprocessed_data/my-gpt2_text_document
                - --vocab-file=gpt2-vocab.json
                - --merge-file=gpt2-merges.txt
                - --data-impl=mmap
                - --split=949,50,1
                - --distributed-backend=nccl
                - --lr=1.5e-4
                - --lr-decay-style=cosine
                - --min-lr=1.0e-5
                - --weight-decay=1e-2
                - --clip-grad=1.0
                - --warmup=0.01
                - --deepspeed-activation-checkpointing
                - --log-interval=1
                - --save-interval=500
                - --eval-interval=100
                - --eval-iters=10
                - --fp16
                - --tensorboard-dir=tensorboard_data/12l_1024h_2n_2g_1pp_1mp_8b_ds4
                - --deepspeed
                - --deepspeed_config=/scripts/zero0.json
                - --deepspeed-activation-checkpointing
                - --checkpoint-num-layers=1
                - --partition-activations
                - --synchronize-each-layer
                - --contigious-checkpointing
                - --deepspeed_mpi
                - --zero-stage=0
#              resources:
#              limits:
#                cpu: 1
#                memory: 2Gi
    Worker:
      replicas: 1
      template:
        spec:
          containers:
            - image: ajliang/dse-experiments
              name: dse-experiments
              volumeMounts:
                - mountPath: /hot
                  name: hot-storage
              resources:
                limits:
                  nvidia.com/gpu: 8
          volumes:
            - name: hot-storage
              persistentVolumeClaim:
                claimName: pollux
          nodeSelector:
            nvidia.com/gpu.product: A100-SXM4-40GB
